// app/[lang]/layout.tsx
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import Header from "../components/Header";
import Footer from "../components/Footer";
import BannerCookie from "@/app/components/BannerCookie";
import { CartProvider } from "@/app/context/CartContext";

import { ClerkProvider } from "@clerk/nextjs";
import { enUS, fiFI, ukUA, ruRU } from "@clerk/localizations";
import { etEE } from "@/app/i18n/clerk-et";

import { getMessages } from "./messages";

type ClerkLocale = typeof enUS;

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const LOCALES = ["en", "et", "fi", "uk", "ru"] as const;
type Locale = (typeof LOCALES)[number];

function isLocale(x: string): x is Locale {
  return (LOCALES as readonly string[]).includes(x);
}

const MAP: Record<Locale, ClerkLocale> = {
  en: enUS,
  et: etEE,
  fi: fiFI,
  uk: ukUA,
  ru: ruRU,
};

export async function generateStaticParams() {
  return LOCALES.map((lang) => ({ lang }));
}

export const metadata: Metadata = {
  title: { default: "Create Next App", template: "%s | Create Next App" },
  description: "Generated by create next app",
};

type LayoutProps = Readonly<{
  children: ReactNode;
  params: Promise<{ lang: string }> | { lang: string };
}>;

export default async function RootLayout({ children, params }: LayoutProps) {
  const resolvedParams = params instanceof Promise ? await params : params;

  // ✅ Next даёт string — приводим к нашему union
  const lang: Locale = isLocale(resolvedParams.lang) ? resolvedParams.lang : "en";

  // ✅ Загружаем переводы один раз на весь layout
  const messages = await getMessages(lang);

  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider localization={MAP[lang]}>
          <CartProvider>
            <Header
              lang={lang}
              messages={{
                HeaderNav: messages.HeaderNav,
                ShoppingCart: messages.ShoppingCart,
              }}
            />

            {children}

            <Footer lang={lang} />
            <BannerCookie lang={lang} />
          </CartProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
